<a href="https://colab.research.google.com/github/ViniciusFebasse/Titanic/blob/main/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [180]:
import pandas as pd
import numpy as np

In [181]:
df_train = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Titanic/train.csv")

In [182]:
df_train.Sex.unique()

array(['male', 'female'], dtype=object)

In [183]:
df_train.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [184]:
df_test = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Titanic/test.csv")

In [185]:
df_test.Sex.unique()

array(['male', 'female'], dtype=object)

In [186]:
df_test.Embarked.unique()

array(['Q', 'S', 'C'], dtype=object)

In [187]:
df_submission = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Titanic/gender_submission.csv")

In [188]:
df_train.head(2)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C

[2 rows x 12 columns]

In [189]:
df_train.shape

(891, 12)

In [190]:
df_test.head(2)

PassengerId  Pclass                              Name  ...    Fare  Cabin  Embarked
0          892       3                  Kelly, Mr. James  ...  7.8292    NaN         Q
1          893       3  Wilkes, Mrs. James (Ellen Needs)  ...  7.0000    NaN         S

[2 rows x 11 columns]

In [191]:
df_test.shape

(418, 11)

In [192]:
df_submission.head(2)

PassengerId  Survived
0          892         0
1          893         1

In [193]:
df_submission.shape

(418, 2)

Pré-processamento

In [194]:
df_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [195]:
# Não foi percebida relação de causa possível com as features: 'PassengerId', 'Name', 'Ticket'
# A feature Cabin possui muitos valores nulos
excluir = ['PassengerId', 'Name', 'Ticket', 'Cabin']
for coluna in excluir:
  df_train.drop(coluna, axis=1, inplace=True)
df_train.head(2)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C

In [196]:
df_train.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [197]:
df_train.Age = df_train.Age.fillna(-1)
df_train.Age.unique()

array([22.  , 38.  , 26.  , 35.  , -1.  , 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [198]:
df_train.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [199]:
df_train.Embarked = df_train.Embarked.dropna(axis=0, how='any')

In [200]:
df_train.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
dtype: int64

In [201]:
X = df_train.drop('Survived', axis=1)
X.head(2)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C

In [202]:
y = df_train.Survived.values
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [203]:
X.head(2)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C

In [204]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
label1 = LabelEncoder()
categoricas = ['Sex', 'Embarked']

X['Sex'] = label.fit_transform(X['Sex'])
X['Embarked'] = label1.fit_transform(X['Embarked'])

In [205]:
X.head(2)

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    1  22.0      1      0   7.2500         2
1       1    0  38.0      1      0  71.2833         0

In [206]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()

X = minmax.fit_transform(X)
X[:3]

array([[1.        , 1.        , 0.28395062, 0.125     , 0.        ,
        0.01415106, 0.66666667],
       [0.        , 0.        , 0.48148148, 0.125     , 0.        ,
        0.13913574, 0.        ],
       [1.        , 0.        , 0.33333333, 0.        , 0.        ,
        0.01546857, 0.66666667]])

In [207]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(668, 7) (223, 7) (668,) (223,)


In [208]:
from sklearn.neural_network import MLPClassifier
neural = MLPClassifier(max_iter=800, random_state=0)

neural.fit(X_train, y_train)

MLPClassifier(max_iter=800, random_state=0)

In [209]:
predicao = neural.predict(X_test)

In [210]:
from sklearn.metrics import accuracy_score

acuracia = accuracy_score(y_test, predicao)

print(f'{np.around(acuracia*100, 2)}%')

81.61%


Previsão

In [211]:
df_test.head(2)

PassengerId  Pclass                              Name  ...    Fare  Cabin  Embarked
0          892       3                  Kelly, Mr. James  ...  7.8292    NaN         Q
1          893       3  Wilkes, Mrs. James (Ellen Needs)  ...  7.0000    NaN         S

[2 rows x 11 columns]

In [212]:
df_test.shape

(418, 11)

In [214]:
df_submissao = df_test['PassengerId']

In [215]:
excluir = ['PassengerId', 'Name', 'Ticket', 'Cabin']
for coluna in excluir:
  df_test.drop(coluna, axis=1, inplace=True)
df_test.head(2)

Pclass     Sex   Age  SibSp  Parch    Fare Embarked
0       3    male  34.5      0      0  7.8292        Q
1       3  female  47.0      1      0  7.0000        S

In [216]:
df_test.Age = df_test.Age.fillna(-1)

In [217]:
df_test.Embarked = df_test.Embarked.dropna(axis=0, how='any')

In [218]:
df_test.head(2)

Pclass     Sex   Age  SibSp  Parch    Fare Embarked
0       3    male  34.5      0      0  7.8292        Q
1       3  female  47.0      1      0  7.0000        S

In [219]:
df_test = df_test.dropna(axis=0, how='any')

In [220]:
df_test.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [221]:
df_test.shape

(417, 7)

In [222]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 417 entries, 0 to 417
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    417 non-null    int64  
 1   Sex       417 non-null    object 
 2   Age       417 non-null    float64
 3   SibSp     417 non-null    int64  
 4   Parch     417 non-null    int64  
 5   Fare      417 non-null    float64
 6   Embarked  417 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 26.1+ KB


In [223]:
X.shape

(891, 7)

In [224]:
df_test['Sex'] = label.transform(df_test['Sex'])
df_test['Embarked'] = label1.transform(df_test['Embarked'])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [225]:
df_test = minmax.transform(df_test)

In [226]:
df_test.shape

(417, 7)

In [230]:
previsao_final = neural.predict(df_test)

In [231]:
df_submission.head(2)

PassengerId  Survived
0          892         0
1          893         1

Montagem do arquivo de submissão

In [232]:
df_submissao

0       892
1       893
2       894
3       895
4       896
       ... 
413    1305
414    1306
415    1307
416    1308
417    1309
Name: PassengerId, Length: 418, dtype: int64

In [233]:
previsao_final = pd.Series(previsao_final)

In [242]:
previsao_final[413]

1

In [243]:
resultado = pd.concat([df_submissao, previsao_final], axis=1)
resultado.head(2)

PassengerId    0
0          892  0.0
1          893  0.0

In [244]:
resultado.columns = ['PassengerId', 'Survived']
resultado.head(2)

PassengerId  Survived
0          892       0.0
1          893       0.0

In [250]:
resultado.Survived = resultado.Survived.astype('int16', errors='ignore')
resultado.head(2)

PassengerId  Survived
0          892       0.0
1          893       0.0